### ISSUE TITLE
Extended canter freezes after landing a jump.

### ISSUE THREAD

**Issue by spacepiratebruh** [cavecomputing/SWEM-Beta#214]
Jumping in an extended canter is fine, but then the animation stops playing after the jump and the horse model reverts back to the still model. you can still move and stuff but it doesn't look like it

**Comment by RileyCasper** [comment]
Assuming because @spacepiratebruh didn't use the template it didn't add an assignee.
@MagnusHJensen as Assignee.

Extending onto this by including examples.

### What happened?
While in extended canter, after a jump horse t-poses.
Animations return after switching gaits.
https://imgur.com/NHK2pOk

### What should happen?
Horse should return to Extended Canter animation after jump.

### Mods
*Assuming it was found on the beta server, self tested in the following environment.*
Optifine
SWEM
Geckolib

**Comment by MagnusHJensen** [comment]
This should have been fixed with the `0.3.6.2-b` release.
Please re-open if persistent.
