### ISSUE TITLE
[Bug]: Horse moves when in rrp command "lay down"

### ISSUE THREAD

**Issue by drakexblud** [cavecomputing/SWEM-Beta#272]
### What happened?

When executing the command /swem rrp laydown, the horse lays down when sat upon but then when pressing shift to dismount the horse, the horse moves a few inches/blocks away from player

### What should happen?

Horse should stay in the position and not move. 

### Mods

SWEM 1.16.5 (Star Worm Equestrian Mod)

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Mothfet** [comment]
/SWEM rrp lay is, as the name implies, a realistic role play command. It is intended to be used for photos or when role playing as a wild horse etc by using invisibility potions. Unfortunately, this means that horses can still technically move as normal, as laying down is not something they do on their on. Likely will not be fixed in 1.16.5, as there are no current plans to update behaviours for this version.
